--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/4/2022 16:49:44
-- Server version: 10.4.22
-- Client version: 4.1
--

--
-- Disable foreign keys
--
/*!40014 set @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;

--
-- Set SQL mode
--
/*!40101 set @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--

set names 'utf8';

--
-- create schema if not exists `mvc`;
--

create schema if not exists `mvc`;

--
-- Set default database
--

use `mvc`;

--
-- Drop table if exists `productos`;
--

drop table if exists `mvc`.`productos`;

--
-- Set default database
--

use `mvc`;

--
-- create table if not exists `mvc`.`productos`
--

create table if not exists `mvc`.`productos`
(
    `id_producto` int(11) unsigned not null unique auto_increment,
    `nombre`      varchar(255) default null,
    `descripcion` varchar(255) default null,
    `precio`      int(11)      default null,
    `stock`       int(11)      default null,
    `imagen`      varchar(255) default null,

    primary key (`id_producto`)
)
    ENGINE = INNODB,
    AUTO_INCREMENT = 27,
    AVG_ROW_LENGTH = 2340,
    CHARACTER SET utf8mb4,
    COLLATE utf8mb4_general_ci;

--
-- Dumping data for table productos
--

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE = @OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;

--
-- Set default database
--

use `mvc`;

--
-- drop table if exists `mvc`.`usuarios`;
--

drop table if exists `mvc`.`usuarios`;

--
-- Set default database
--

use `mvc`;

--
-- create table if not exists `mvc`.`usuarios`
--

create table if not exists `mvc`.`usuarios`
(
    `id_usuario` int(11) unsigned not null unique auto_increment,
    `username`   varchar(255)     not null,
    `email`      varchar(255)     not null,
    `password`   varchar(255)     not null,
    `isAdmin`    boolean          not null default false,
    primary key (`id_usuario`)
)
    ENGINE = INNODB,
    AUTO_INCREMENT = 4,
    AVG_ROW_LENGTH = 8192,
    CHARACTER SET utf8mb4,
    COLLATE utf8mb4_general_ci;

--
-- Set default database
--

use `mvc`;

--
-- drop table if exists `mvc`.`orden_compra`;
--

drop table if exists `mvc`.`orden_compra`;

--
-- Set default database
--

use `mvc`;

--
-- create table if not exists `mvc`.`orden_compra`
--

create table if not exists `mvc`.`orden_compra`
(
    `id_orden_compra` int(11) unsigned                                            not null unique auto_increment,
    `id_usuario`      int(11) unsigned                                            not null,
    `nombre`          varchar(60)                                                 not null,
    `apellido`        varchar(60)                                                 not null,
    `telefono`        int(20) unsigned                                            not null,
    `direccion`       varchar(60)                                                 not null,
    `provincia`       varchar(20)                                                 not null,
    `codigo_postal`   varchar(5)                                                  not null,
    `estado`          enum ('en_proceso', 'despachada', 'cancelada', 'entregada') not null default 'en_proceso',
    `fecha`           datetime                                                    not null default current_timestamp,

    primary key (`id_orden_compra`),
    foreign key (`id_usuario`) references `mvc`.`usuarios` (`id_usuario`),
    index `fk_orden_compra_usuario` (`id_usuario` asc)
);

--
-- Set default database
--

use `mvc`;

--
-- drop table if exists `mvc`.`orden_producto`;
--

drop table if exists `mvc`.`orden_producto`;

--
-- Set default database
--

use `mvc`;

--
-- create table if not exists `mvc`.`orden_producto`
--

create table if not exists `mvc`.`orden_producto`
(
    `id_orden_producto` int(11) unsigned not null unique auto_increment,
    `id_orden_compra`   int(11) unsigned not null,
    `id_producto`       int(11) unsigned not null,
    `cantidad`          tinyint unsigned not null,

    primary key (`id_orden_producto`),
    foreign key (`id_orden_compra`) references `mvc`.`orden_compra` (`id_orden_compra`),
    index `fk_orden_producto` (`id_orden_compra` asc),
    foreign key (`id_producto`) references `mvc`.`productos` (`id_producto`),
    index `fk_producto_orden` (`id_producto` asc)
);

--
-- Set default database
--

use `mvc`;

--
-- INSERT INTO `mvc`.`productos`
--

INSERT INTO `mvc`.`productos`(`nombre`, `descripcion`, `precio`, `stock`, `imagen`)
VALUES ('Bob Esponja, burbuja', 'Taza Bob Esponja ', 1000, 5, '20220401_BS.jpg'),
       ('Bob Esponja, amigos ', 'Taza Bob Esponja ', 1000, 10, '20220402_BS.jpg'),
       ('Harry Potter', 'Muggles', 1100, 4, '20220408_HP.jpg'),
       ('Harry Potter', 'Leviosa', 1100, 4, '20220407_HP.jpg'),
       ('Rick y Morty', 'Get Schwifty', 1000, 10, '20220403_RM.jpg'),
       ('Rick y Morty', 'Free Rick', 1000, 10, '20220404_RM.jpg'),
       ('Caballeros del Zodiaco', 'Leo', 800, 3, '20220405_CZ.jpg'),
       ('Caballeros del Zodiaco', 'Aries', 800, 5, '20220406_CZ.jpg'),
       ('Los Simpson', 'Ralph', 900, 8, '20220409_LS.jpeg'),
       ('Los Simpson', 'Llamarada Moe', 900, 6, '20220410_LS.jpeg'),
       ('Doctor Strange', 'Taza Doctor Strange', 1200, 7, '20220411_DS.jpeg'),
       ('Doctor Strange', 'Taza Doctor Strange', 1200, 7, '20220412_DS.jpeg');

--
-- Set default database
--

use `mvc`;

--
-- INSERT INTO `mvc`.`usuarios`
--

insert into `usuarios`(username, email, password, isAdmin)
values ('admin', 'admin@admin.com',
        '$2y$10$kgJGtMN5YoNlvEyVUKAqq.BXYtqPAIT3g3Z6wuEuwD3lIVLTQU0dK', 1); -- contraseña igual a '123'